[package]
name = "refraktal-io"
description = "File loading and saving for Refraktal"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.104"
hound = "3.5.1"
refraktal-dsp.workspace = true
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
symphonia = { version = "0.6.1", features = ["mp3"] }
